name: Generate SBOM

on: [push]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
      - name: Install CycloneDX
        run: npm install -g @cyclonedx/bom
      - name: Install dependencies
        run: npm install
      - name: Generate SBOM
        run: cyclonedx-bom -o sbom.json
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json

